DROP TABLE IF EXISTS servers;
DROP TABLE IF EXISTS users;

CREATE TABLE servers (
  id TEXT PRIMARY KEY UNIQUE 
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT,
  points INTEGER,
  serverId TEXT,
  FOREIGN KEY(serverId) REFERENCES servers(id)
)


